# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@2ded56de883b35b1e18b37566fd406625153f1e2
    with:
      release_files: bazel_terraform-*.tar.gz
      prerelease: false
