name: Update Versions PR

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror versions
        id: mirror-versions
        run: |-
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          bazel run //scripts:mirror_terraform_releases

      - name: Create PR
        if: steps.mirror-versions.outputs.has_changes
        run: >-
          gh pr create --base main --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
