name: Update Versions PR

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch versions
        run: |-
          bazel run //scripts:mirror_terraform_releases > terraform/private/versions_new.bzl

      - name: Commit and push update
        run: |-
          mv terraform/private/versions_new.bzl terraform/private/versions.bzl
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b update-terraform-versions
          git add terraform/private/versions.bzl
          git commit -m "Updated Terraform Versions"
          git push origin -u update-terraform-versions

      - name: Create PR
        run: >-
          gh pr create --base main --title 'Update Terraform Versions' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
